### ISSUE TITLE
Access to care section is missing disclaimer

### ISSUE THREAD

**Issue by gnakm** [department-of-veterans-affairs/vets-website#3848]
<img width="355" alt="screen shot 2016-11-08 at 6 22 15 pm" src="https://cloud.githubusercontent.com/assets/13420618/20121574/4f80bde0-a5e0-11e6-9a8d-0d5380c3bf0c.png">

<img width="340" alt="screen shot 2016-11-08 at 6 22 41 pm" src="https://cloud.githubusercontent.com/assets/13420618/20121579/5d35d416-a5e0-11e6-8fa6-2ba7fd785590.png">

Above table:
Current as of **November 1, 2015 - April 30, 2016**

Below table:
[Asterisk] % of Veterans who reported that they were "Always" or "Usually" able to get an appointment.

**Comment by bshyong** [comment]
resolved by https://github.com/department-of-veterans-affairs/vets-website/pull/3852

**Comment by gnakm** [comment]
@bshyong 

We are still missing Current as of date range under the access to care header. 

<img width="333" alt="screen shot 2016-11-09 at 1 50 13 pm" src="https://cloud.githubusercontent.com/assets/13420618/20150357/7ba8368e-a683-11e6-8e2b-2dd1b49264fa.png">

This is super minor. Could we un-italicize the disclaimer at the bottom?

**Comment by NatalieEMoore** [comment]
Sorry but @ben @gnakm is it possible to remove the * and have it say Note: % of Veterans who reported that they were "Always" or Usually" able to get appointment.

**Comment by NatalieEMoore** [comment]
And making sure we also include the "Current as of November 1, 2015 - April 30, 2016".
